import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Bounce, Slide, ToastContainer } from "react-toastify";
import NavBar from "@/components/NavBar";
import { Urbanist } from "next/font/google";


const urbanist = Urbanist({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Carbon Credits Dapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`antialiased ${urbanist.className}`}
      >
      <ToastContainer
        position="top-right"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick={false}
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="colored"
        transition={Slide}
      />
      <NavBar />
        {children}
      </body>
    </html>
  );
}
